export const AllSkills = [
  {
    id: 1,
    title: "NextJS",
    color: "rose",
    borderColor: "rose",
  },
  {
    id: 2,
    title: "React Native",
    color: "teal",
    borderColor: "teal",
  },
  {
    id: 3,
    title: "Golang",
    color: "pink",
    borderColor: "pink",
  },
  {
    id: 4,
    title: "Javascript",
    color: "violet",
    borderColor: "violet",
  },
  {
    id: 5,
    title: "Typescript",
    color: "purple",
    borderColor: "purple",
  },
  {
    id: 6,
    title: "HTML5",
    color: "sky",
    borderColor: "sky",
  },
  {
    id: 7,
    title: "CSS3",
    color: "yellow",
    borderColor: "yellow",
  },
  {
    id: 8,
    title: "TailwindCSS",
    color: "green",
    borderColor: "green",
  },
  {
    id: 9,
    title: "NodeJS",
    color: "gray",
    borderColor: "gray",
  },
  {
    id: 10,
    title: "MongoDB",
    color: "red",
    borderColor: "red",
  },
  {
    id: 11,
    title: "Express",
    color: "indigo",
    borderColor: "indigo",
  },
  {
    id: 12,
    title: "Java",
    color: "cyan",
    borderColor: "cyan",
  },
  {
    id: 13,
    title: "GraphQL",
    color: "rose",
    borderColor: "rose",
  },
  {
    id: 14,
    title: "Git",
    color: "teal",
    borderColor: "teal",
  },
  {
    id: 15,
    title: "SQL/NoSQL",
    color: "pink",
    borderColor: "pink",
  },
  {
    id: 16,
    title: "Prisma",
    color: "violet",
    borderColor: "violet",
  },
  {
    id: 17,
    title: "Zustand/ RTK",
    color: "purple",
    borderColor: "purple",
  },
  {
    id: 18,
    title: "Linux",
    color: "Lime",
    borderColor: "Lime",
  },
  {
    id: 19,
    title: "Docker",
    color: "yellow",
    borderColor: "yellow",
  },
  {
    id: 20,
    title: "TRPC",
    color: "lightBlue",
    borderColor: "lightBlue",
  },
  {
    id: 21,
    title: "FastAPI",
    color: "pink",
    borderColor: "pink",
  },
  {
    id: 22,
    title: "MySQL",
    color: "purple",
    borderColor: "purple",
  },
  {
    id: 23,
    title: "Azure",
    color: "zinc",
    borderColor: "zinc",
  },
  {
    id: 24,
    title: "Jest",
    color: "teal",
    borderColor: "teal",
  },
  {
    id: 25,
    title: "Redis",
    color: "rose",
    borderColor: "rose",
  },
  {
    id: 26,
    title: "NestJS",
    color: "Lime",
    borderColor: "Lime",
  },
  {
    id: 27,
    title: "Firebase",
    color: "teal",
    borderColor: "teal",
  },
  {
    id: 28,
    title: "Langchain",
    color: "purple",
    borderColor: "purple",
  },
  {
    id: 29,
    title: "DataStax/Chroma",
    color: "red",
    borderColor: "red",
  },
  {
    id: 30,
    title: "GenAI",
    color: "indigo",
    borderColor: "indigo",
  },
];
